# Generated by Django 4.2.4 on 2023-09-02 04:42

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_statcategory_units_alter_stats_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpost',
            name='body',
            field=wagtail.fields.StreamField([('gallery', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock)), ('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], use_json_field=True),
        ),
    ]
