# Generated by Django 4.2.4 on 2023-09-02 04:52

from django.db import migrations
import projects.models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projectpost_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpost',
            name='body',
            field=wagtail.fields.StreamField([('gallery', wagtail.blocks.ListBlock(projects.models.GalleryBlock)), ('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], use_json_field=True),
        ),
    ]
