# Generated by Django 4.1.4 on 2023-09-04 04:42

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_projectpost_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpost',
            name='intro_img',
            field=wagtail.fields.StreamField([('gallery', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('caption', wagtail.blocks.CharBlock()), ('img', wagtail.images.blocks.ImageChooserBlock())])))], null=True, use_json_field=True),
        ),
    ]
