# Generated by Django 4.0.3 on 2022-07-13 04:55
from django.db import migrations
from django.conf import settings

def update_site_name(apps, schema_editor):
    SiteModel = apps.get_model('sites', 'Site')
    domain = 'terravenusta.com'

    SiteModel.objects.update_or_create(
        pk=settings.SITE_ID,
        defaults={'domain': domain,
                  'name': domain}
    )

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_options_alter_thread_options_and_more'),
    ]

    operations = [
        migrations.RunPython(update_site_name),
    ]
