# Generated by Django 4.0.3 on 2022-08-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsblog', '0002_rename_post_blogpost_blogindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='intro',
            field=models.CharField(default='Intro text', max_length=1000),
            preserve_default=False,
        ),
    ]
