# Generated by Django 4.1 on 2022-09-02 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsblog', '0005_rename_user_blogpost_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['first_published_at']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='pub_date',
            new_name='first_published_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='edit_date',
            new_name='last_published_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='edit_date',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
