# Generated by Django 4.1 on 2022-09-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsblog', '0006_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edits',
            field=models.PositiveIntegerField(default=0, verbose_name='number of edits'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='first_published_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
