# Generated by Django 4.1 on 2022-10-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsblog', '0008_comment_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='flagged_count',
            field=models.PositiveIntegerField(default=0, verbose_name='number of times this comment has been flagged'),
        ),
    ]
